import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/variables.css"
import { HomeHeader } from "@/widgets";

export const metadata: Metadata = {
  title: "Linkedin",
  description: "Generated by best developers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HomeHeader />
        {children}
      </body>
    </html>
  );
}
